export const PLAYBOOK_CATALOG = [
  {
    id: "playbook-01",
    name: "security hot motion",
    priority: 90,
    when: {
      bands: ["hot"],
      terms: ["security"],
      blockers: ["legal"],
      minScore: 70,
    },
    actions: [
      "Confirm security owner",
      "Send security proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-02",
    name: "pilot warm motion",
    priority: 89,
    when: {
      bands: ["warm"],
      terms: ["pilot"],
      blockers: ["pricing"],
      minScore: 45,
    },
    actions: [
      "Confirm pilot owner",
      "Send pilot proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-03",
    name: "procurement watch motion",
    priority: 88,
    when: {
      bands: ["watch"],
      terms: ["procurement"],
      blockers: ["procurement"],
      minScore: 0,
    },
    actions: [
      "Confirm procurement owner",
      "Send procurement proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-04",
    name: "pricing hot motion",
    priority: 87,
    when: {
      bands: ["hot"],
      terms: ["pricing"],
      blockers: ["security"],
      minScore: 70,
    },
    actions: [
      "Confirm pricing owner",
      "Send pricing proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-05",
    name: "integration warm motion",
    priority: 86,
    when: {
      bands: ["warm"],
      terms: ["integration"],
      blockers: ["legal"],
      minScore: 45,
    },
    actions: [
      "Confirm integration owner",
      "Send integration proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-06",
    name: "stakeholder watch motion",
    priority: 85,
    when: {
      bands: ["watch"],
      terms: ["stakeholder"],
      blockers: ["pricing"],
      minScore: 0,
    },
    actions: [
      "Confirm stakeholder owner",
      "Send stakeholder proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-07",
    name: "timeline hot motion",
    priority: 84,
    when: {
      bands: ["hot"],
      terms: ["timeline"],
      blockers: ["procurement"],
      minScore: 70,
    },
    actions: [
      "Confirm timeline owner",
      "Send timeline proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-08",
    name: "security warm motion",
    priority: 83,
    when: {
      bands: ["warm"],
      terms: ["security"],
      blockers: ["security"],
      minScore: 45,
    },
    actions: [
      "Confirm security owner",
      "Send security proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-09",
    name: "pilot watch motion",
    priority: 82,
    when: {
      bands: ["watch"],
      terms: ["pilot"],
      blockers: ["legal"],
      minScore: 0,
    },
    actions: [
      "Confirm pilot owner",
      "Send pilot proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-10",
    name: "procurement hot motion",
    priority: 81,
    when: {
      bands: ["hot"],
      terms: ["procurement"],
      blockers: ["pricing"],
      minScore: 70,
    },
    actions: [
      "Confirm procurement owner",
      "Send procurement proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-11",
    name: "pricing warm motion",
    priority: 80,
    when: {
      bands: ["warm"],
      terms: ["pricing"],
      blockers: ["procurement"],
      minScore: 45,
    },
    actions: [
      "Confirm pricing owner",
      "Send pricing proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-12",
    name: "integration watch motion",
    priority: 79,
    when: {
      bands: ["watch"],
      terms: ["integration"],
      blockers: ["security"],
      minScore: 0,
    },
    actions: [
      "Confirm integration owner",
      "Send integration proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-13",
    name: "stakeholder hot motion",
    priority: 78,
    when: {
      bands: ["hot"],
      terms: ["stakeholder"],
      blockers: ["legal"],
      minScore: 70,
    },
    actions: [
      "Confirm stakeholder owner",
      "Send stakeholder proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-14",
    name: "timeline warm motion",
    priority: 77,
    when: {
      bands: ["warm"],
      terms: ["timeline"],
      blockers: ["pricing"],
      minScore: 45,
    },
    actions: [
      "Confirm timeline owner",
      "Send timeline proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-15",
    name: "security watch motion",
    priority: 76,
    when: {
      bands: ["watch"],
      terms: ["security"],
      blockers: ["procurement"],
      minScore: 0,
    },
    actions: [
      "Confirm security owner",
      "Send security proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-16",
    name: "pilot hot motion",
    priority: 75,
    when: {
      bands: ["hot"],
      terms: ["pilot"],
      blockers: ["security"],
      minScore: 70,
    },
    actions: [
      "Confirm pilot owner",
      "Send pilot proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-17",
    name: "procurement warm motion",
    priority: 74,
    when: {
      bands: ["warm"],
      terms: ["procurement"],
      blockers: ["legal"],
      minScore: 45,
    },
    actions: [
      "Confirm procurement owner",
      "Send procurement proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-18",
    name: "pricing watch motion",
    priority: 73,
    when: {
      bands: ["watch"],
      terms: ["pricing"],
      blockers: ["pricing"],
      minScore: 0,
    },
    actions: [
      "Confirm pricing owner",
      "Send pricing proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-19",
    name: "integration hot motion",
    priority: 72,
    when: {
      bands: ["hot"],
      terms: ["integration"],
      blockers: ["procurement"],
      minScore: 70,
    },
    actions: [
      "Confirm integration owner",
      "Send integration proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-20",
    name: "stakeholder warm motion",
    priority: 71,
    when: {
      bands: ["warm"],
      terms: ["stakeholder"],
      blockers: ["security"],
      minScore: 45,
    },
    actions: [
      "Confirm stakeholder owner",
      "Send stakeholder proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-21",
    name: "timeline watch motion",
    priority: 70,
    when: {
      bands: ["watch"],
      terms: ["timeline"],
      blockers: ["legal"],
      minScore: 0,
    },
    actions: [
      "Confirm timeline owner",
      "Send timeline proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-22",
    name: "security hot motion",
    priority: 69,
    when: {
      bands: ["hot"],
      terms: ["security"],
      blockers: ["pricing"],
      minScore: 70,
    },
    actions: [
      "Confirm security owner",
      "Send security proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-23",
    name: "pilot warm motion",
    priority: 68,
    when: {
      bands: ["warm"],
      terms: ["pilot"],
      blockers: ["procurement"],
      minScore: 45,
    },
    actions: [
      "Confirm pilot owner",
      "Send pilot proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-24",
    name: "procurement watch motion",
    priority: 67,
    when: {
      bands: ["watch"],
      terms: ["procurement"],
      blockers: ["security"],
      minScore: 0,
    },
    actions: [
      "Confirm procurement owner",
      "Send procurement proof package",
      "Create security mitigation task",
    ],
  },
  {
    id: "playbook-25",
    name: "pricing hot motion",
    priority: 66,
    when: {
      bands: ["hot"],
      terms: ["pricing"],
      blockers: ["legal"],
      minScore: 70,
    },
    actions: [
      "Confirm pricing owner",
      "Send pricing proof package",
      "Create legal mitigation task",
    ],
  },
  {
    id: "playbook-26",
    name: "integration warm motion",
    priority: 65,
    when: {
      bands: ["warm"],
      terms: ["integration"],
      blockers: ["pricing"],
      minScore: 45,
    },
    actions: [
      "Confirm integration owner",
      "Send integration proof package",
      "Create pricing mitigation task",
    ],
  },
  {
    id: "playbook-27",
    name: "stakeholder watch motion",
    priority: 64,
    when: {
      bands: ["watch"],
      terms: ["stakeholder"],
      blockers: ["procurement"],
      minScore: 0,
    },
    actions: [
      "Confirm stakeholder owner",
      "Send stakeholder proof package",
      "Create procurement mitigation task",
    ],
  },
  {
    id: "playbook-28",
    name: "timeline hot motion",
    priority: 63,
    when: {
      bands: ["hot"],
      terms: ["timeline"],
      blockers: ["security"],
      minScore: 70,
    },
    actions: [
      "Confirm timeline owner",
      "Send timeline proof package",
      "Create security mitigation task",
    ],
  },
];
